language: node_js
node_js:
    # XXX right now, segfaulting on the 500MB upload
    # - "0.11"
    - "0.10"

env:
    # Don't know yet how to install etcd on travis ubuntu, so disable the tests
    - NO_ETCD=true

before_install:
    - sudo apt-get update
    - sudo apt-get install redis-server memcached
    - npm install -g gulp
    - sudo apt-get install python-pip

before_script:
    # Hinting - XXX should fail!
    - npm run-script hint
    - redis-server &

after_script:
    # Coveralls report
    - npm run coveralls
    # Pythonic tests require
    - ./bin/hipache -c config/config_test.json &
    # Running pythonic functional tests
    - (cd test/functional && sudo pip install -r requirements.txt)
    - (cd test/functional && python -m unittest discover)
